<?php

namespace adminBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function categorie()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('COUNT(cat)')
            ->from('adminBundle:Categorie', 'cat')
            ->getQuery();

        die(dump($query->getSingleScalarResult()));
    }

    public function categorieActive()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('COUNT(cat)')
            ->from('adminBundle:Categorie', 'cat')
            ->where('cat.active=1')
            ->getQuery();

        die(dump($query->getOneOrNullResult()));
    }


}


